apiVersion: apps/v1
kind: Deployment
metadata:
  name: getpod
  namespace: default
spec:
  selector:
    matchLabels:
      app: getpod
  replicas: 1
  template:
    metadata:
      labels:
        app: getpod
    spec:
      containers:
      - name: getpod
        image: ghcr.io/duyhenryer/getpod:main@sha256:9586997dd64a6b66f77534b698966f303dfc7a42854bb53ef6826865877769ba
        env:
        - name: K8S_DEMO_APP_MESSAGE
          value: "Hello Getpod!"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: getpod
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: getpod
